name: Dev CI

on:
  push:
    branches:
      - 'dev'

jobs:
  sonarqube:
    name: Sonarqube analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: sonarsource/sonarqube-scan-action@master
        with:
          args: >
            -Dsonar.branch.name=dev
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
  docker:
    name: Build docker image and push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Cloud Coding Registry
        uses: docker/login-action@v1
        with:
          registry: rg.fr-par.scw.cloud/cloudcoding
          username: nologin
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: rg.fr-par.scw.cloud/cloudcoding/cloudcoding-angular-app:dev
  keel:
    name: Deploy new version
    runs-on: ubuntu-latest
    needs:
      - docker
    steps:
      - name: Keel webhook
        uses: jaapio/keelsh-deploy@master
        with:
          keelBaseUrl: https://keel.cloudcoding.fr
          image: rg.fr-par.scw.cloud/cloudcoding/cloudcoding-angular-app
          tag: dev
